#!/usr/bin/env python
import numpy as np
from scipy.ndimage import minimum_filter
import sys
from pprint import pformat

def find_local_minima(rmsd, overlap, params, rmsd_cutoff=0.5, neighborhood_size=3):
    """
    Find local minima in the RMSD landscape.
    """
    # Create mask for valid regions (has overlap and below cutoff)
    valid_mask = (overlap > 0) & (rmsd < rmsd_cutoff)
    
    # Apply minimum filter
    local_min = minimum_filter(rmsd, size=neighborhood_size)
    
    # Find local minima positions
    is_local_min = (rmsd == local_min) & valid_mask
    
    # Get indices of local minima
    min_indices = np.where(is_local_min)
    
    # Convert indices to physical values
    tilts = np.array(list(params['tilt_range'])) * params['tilt_scale']
    radii = np.array(list(params['radius_range'])) * params['radius_scale']
    
    # Collect results - explicitly convert numpy types to Python built-in types
    minima = []
    for i, j in zip(*min_indices):
        minima.append({
            'tilt': float(tilts[i]),
            'radius': float(radii[j]),
            'rmsd': float(rmsd[i, j]),
            'overlap': int(overlap[i, j]),
            'tilt_idx': int(i),
            'radius_idx': int(j)
        })
    
    # Sort by radius
    minima.sort(key=lambda x: x['radius'])
    
    return minima

def save_minima_to_python(all_results, filename="minima_data.py"):
    """Save minima data in a Python-importable format"""
    with open(filename, 'w') as f:
        f.write("#!/usr/bin/env python\n")
        f.write("# Generated by find_minima.py\n\n")
        f.write("# Dictionary format:\n")
        f.write("# Key: PDB prefix (e.g., '80.439.240.45')\n")
        f.write("# Value: List of dictionaries containing:\n")
        f.write("#   - tilt: tilt angle in degrees\n")
        f.write("#   - radius: radius in Angstroms\n")
        f.write("#   - rmsd: RMSD value in Angstroms\n")
        f.write("#   - overlap: number of overlapping points\n")
        f.write("#   - tilt_idx: index in tilt array\n")
        f.write("#   - radius_idx: index in radius array\n\n")
        f.write("minima_data = ")
        
        # Ensure all numpy types are converted to Python built-in types
        clean_results = {k: [
            {kk: float(vv) if isinstance(vv, np.floating) else int(vv) if isinstance(vv, np.integer) else vv 
             for kk, vv in m.items()}
            for m in v
        ] for k, v in all_results.items()}
        
        f.write(pformat(clean_results))
        f.write("\n")

def analyze_pdb(pdb_prefix, rmsd_cutoff=0.5):
    """Analyze a single PDB file"""
    # Load data
    rmsd = np.load(f'rmsd_{pdb_prefix}.npy')
    overlap = np.load(f'overlap_{pdb_prefix}.npy')
    params = np.load('scan_params.npy', allow_pickle=True).item()
    
    # Find minima
    minima = find_local_minima(rmsd, overlap, params, rmsd_cutoff)
    
    # Print results
    print(f"\nResults for {pdb_prefix}:")
    print(f"Found {len(minima)} local minima with RMSD < {rmsd_cutoff}Å")
    print("\nAll local minima (sorted by radius):")
    print("Radius(Å)  Tilt(°)  RMSD(Å)  #Overlap")
    print("-" * 45)
    
    for m in minima:
        print(f"{m['radius']:8.1f}  {m['tilt']:6.1f}  {m['rmsd']:7.3f}  {m['overlap']:8d}")
        
    return minima

def analyze_all_pdbs(rmsd_cutoff=0.5):
    """Analyze all available RMSD data files"""
    import glob
    import os
    
    # Find all RMSD data files
    rmsd_files = glob.glob('rmsd_*.npy')
    all_results = {}
    
    for rmsd_file in rmsd_files:
        # Skip the best_rmsd file
        if rmsd_file == 'rmsd_best.npy':
            continue
        
        # Extract PDB prefix and analyze
        pdb_prefix = os.path.splitext(rmsd_file)[0].replace('rmsd_', '')
        all_results[pdb_prefix] = analyze_pdb(pdb_prefix, rmsd_cutoff)
    
    # Save results to Python file
    save_minima_to_python(all_results)
    
    return all_results

if __name__ == '__main__':
    # Set RMSD cutoff
    RMSD_CUTOFF = 1.0
    
    if len(sys.argv) > 1:
        # Analyze specific PDB
        results = {sys.argv[1]: analyze_pdb(sys.argv[1], RMSD_CUTOFF)}
        save_minima_to_python(results)
    else:
        # Analyze all PDbs
        all_results = analyze_all_pdbs(RMSD_CUTOFF)
